name: Close Issue on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  close-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Close issue
        if: github.event.pull_request.merged == true
        run: echo "Issue automatically closed on merge"
